package carrot.ez.service;

import carrot.ez.dto.LotteryStatisticsDto;
import carrot.ez.lotto.Lotteries;
import carrot.ez.lotto.Lottery;
import carrot.ez.dto.WinningNumberDto;
import carrot.ez.lotto.Rank;

import java.util.Map;

public class LottoService {
    
    public Lotteries purchaseLotteries(long amount) {
        long numLotteries  = amount / Lottery.LOTTO_PRICE;
        return Lotteries.createAutoGeneratedLotteries(numLotteries);
    }

    public LotteryStatisticsDto checkWiningNumbers(Lotteries lotteries, WinningNumberDto winningNumberDto) {
        Map<Rank, Long> rankCountMap = lotteries.checkWinningNumbers(winningNumberDto.getWinningNumber(), winningNumberDto.getBonus());
        Long sum = rankCountMap.entrySet().stream()
                .map(entry -> entry.getKey().getPrice() * entry.getValue())
                .reduce(Long::sum)
                .orElseThrow();
        return new LotteryStatisticsDto(rankCountMap, sum);
    }
}
