drop table if exists lottos CASCADE;
create table lottos
(
    id   bigint generated by default as identity,
    numbers varchar(22),
    primary key (id)
);

drop table if exists matches CASCADE;
create table matches
(
    rank varchar(6),
    count int,
    primary key (rank)
);

insert into matches(rank, count) values('first', 0);
insert into matches(rank, count) values('second', 0);
insert into matches(rank, count) values('third', 0);
insert into matches(rank, count) values('fourth', 0);
insert into matches(rank, count) values('fifth', 0);