/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package be.w2.lotto;

import org.junit.jupiter.api.Test;

class LottoApplicationTest {
    @Test void appHasAGreeting() {
        LottoApplication classUnderTest = new LottoApplication();
    }
}
