package application;

import domain.Lotto;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class AutoGeneratedLottoPurchaserTest {
    private final int PURCHASE_NUMBER = 14;

    @DisplayName("N개의 로또 구매의 성공을 검증")
    @Test
    void areNOfLottoPurchaseSuccessful() {
        AutoGeneratedLottoPurchaser purchaser = new AutoGeneratedLottoPurchaser(PURCHASE_NUMBER);

        List<Lotto> lottoList = purchaser.generateLotto();

        assertThat(lottoList.size())
                .isEqualTo(PURCHASE_NUMBER);
    }

}