package application;

import domain.Lotto;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class AutoGeneratedLottoPurchaserTest {
    private static final int PURCHASE_QUANTITY = 14;

    @DisplayName("입력 개수만큼 로또가 생성되었는지 검증")
    @Test
    void N개로또_생성_테스트() {
        // given
        AutoGeneratedLottoPurchaser lottoPurchaser = new AutoGeneratedLottoPurchaser();

        // when
        List<Lotto> lottoList = lottoPurchaser.generateLotto(PURCHASE_QUANTITY);

        //then
        assertThat(lottoList.size())
                .isEqualTo(PURCHASE_QUANTITY);
    }
}