/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lotto;

import lotto.controller.LottoController;

import java.io.*;

public class App {

    public static void main(String[] args) {
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
             BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(System.out))) {
            LottoController lottoController = new LottoController(writer, reader);
            lottoController.lottoStart();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
