/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lotto;

import lotto.domain.Lotto;
import lotto.view.InputView;
import lotto.view.OutputView;

import java.util.ArrayList;

public class LottoApp {

    public static void main(String[] args){

        int bonusBall;
        int moneyToGame = InputView.inputPurchaseAmount();
        ArrayList<Integer> winningNumber;

        Lotto lotto = new Lotto(moneyToGame);
        OutputView.displayPurchaseGames(lotto.getNumberGames());
        OutputView.displayPurchasedNumbers(lotto.getLottoGames());

        winningNumber = InputView.inputWinningNumber();
        bonusBall = InputView.inputBonusNumber();

        lotto.checkWinning(winningNumber, bonusBall);
        OutputView.displayWinningResults(lotto);
    }

}
