/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lotto;

import lotto.domain.LottoBuyer;

public class LottoApp {
    public static void main(String[] args) {
        LottoBuyer lottoBuyer = new LottoBuyer();
        lottoBuyer.start();
    }
}
