/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lotto;

import lotto.domain.LottoGames;
import lotto.domain.WinningLotto;
import lotto.view.InputView;
import lotto.view.OutputView;

import java.util.ArrayList;

public class LottoApp {

    public static void main(String[] args){

        int moneyToGame = InputView.inputPurchaseAmount();
        ArrayList<Integer> winningNumber;
        ArrayList<ArrayList<Integer>> manualNumbers;

        int manualGame = InputView.inputManualGame();
        manualNumbers = InputView.inputManualNumber(manualGame);

        LottoGames lottoGames = LottoGames.of(moneyToGame);
        lottoGames.inputManualNumbers(manualNumbers);
        OutputView.displayPurchaseGames(lottoGames.getManualGames(), lottoGames.getAutoGames());
        OutputView.displayPurchasedNumbers(lottoGames.getLottoGames());

        winningNumber = InputView.inputWinningNumber();
        int bonusBall = InputView.inputBonusNumber();

        WinningLotto winningLotto = WinningLotto.of(winningNumber, bonusBall);
        winningLotto.checkWinning(lottoGames.getLottoGames());
        OutputView.displayWinningResults(winningLotto);
    }

}
