package application;

import domain.Lotto;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public class AutoGeneratedLottoPurchaser implements LottoPurchaser {
    @Override
    public List<Lotto> generateLotto(int quantity) {
        LottoGenerator lottoGenerator = new AutoLottoGenerator();
        return IntStream.range(0, quantity)
                .mapToObj(e -> lottoGenerator.getLotto())
                .collect(Collectors.toList());
    }
}
