package application;

import domain.Lotto;
import domain.WinningLotto;
import view.LottoGuidePrinter;
import view.LottoScanner;

import java.util.List;

public class LottoManager {

    public static void run() {
        int purchaseQuantity = inputPurchaseQuantity();
        purchaseAutoGeneratedLotto(purchaseQuantity);
        Lotto winningLotto = inputWinnningLotto();
    }


    private static int inputPurchaseQuantity() {
        int purchaseQuantity = LottoScanner.getPurchaseQuantity();
        LottoGuidePrinter.alertPurchaseQuantity(purchaseQuantity);
        return purchaseQuantity;
    }

    private static void purchaseAutoGeneratedLotto(int purchaseQuantity) {
        AutoGeneratedLottoPurchaser lottoPurchaser = new AutoGeneratedLottoPurchaser();
        List<Lotto> lottoList = lottoPurchaser.generateLotto(purchaseQuantity);
        LottoGuidePrinter.printLottoList(lottoList);
    }

    private static Lotto inputWinnningLotto() {
        LottoGenerator lottoGenerator = new WinningLottoGenerator();
        return lottoGenerator.getLotto();
    }
}
