/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package be.w2.lotto;

import be.w2.lotto.domain.LottoTickets;
import be.w2.lotto.domain.WinningLottoTicket;
import be.w2.lotto.domain.WinningResult;
import be.w2.lotto.dto.LottoTicketsDto;
import be.w2.lotto.dto.WinningResultDto;
import be.w2.lotto.view.InputView;
import be.w2.lotto.view.OutputView;

import static be.w2.lotto.view.InputView.inputPurchaseAmount;

public class LottoApplication {

    public static void main(String[] args) {
        int purchaseAmount = inputPurchaseAmount();
        LottoTickets lottoTickets = LottoTickets.valueOf(purchaseAmount);
        LottoTicketsDto lottoTicketsDto = LottoTicketsDto.from(lottoTickets);

        OutputView.outputLottoAmounts(lottoTicketsDto.getLottoTicketAmount());
        OutputView.outputLottoTickets(lottoTicketsDto.getLottoTickets());
        String winningNumbers = InputView.inputWiningNumbers();
        WinningLottoTicket winningLottoTicket = WinningLottoTicket.valueOf(winningNumbers);
        WinningResult winningResult = WinningResult.valueOf(lottoTickets, winningLottoTicket, purchaseAmount);
        WinningResultDto winningResultDto = WinningResultDto.from(winningResult);
        OutputView.outputWinningResult(winningResultDto);
    }
}
