/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lotto;

import lotto.domain.LottoGames;
import lotto.domain.WinningLotto;
import lotto.view.OutputView;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {

    @DisplayName("전체 LottoGames 테스트")
    @Test
    void lottoTest(){
        int bonusBall;
        int moneyToGame = 3000;
        ArrayList<Integer> winningNumber;

        LottoGames lottoGames = LottoGames.of(moneyToGame);
        lottoGames.inputManualNumbers(new ArrayList<ArrayList<Integer>>(Arrays.asList(new ArrayList<Integer>(Arrays.asList(1,2,3,4,5,6)), new ArrayList<Integer>(Arrays.asList(2,3,4,5,6,7)))));
        OutputView.displayPurchaseGames(lottoGames.getManualGames(), lottoGames.getAutoGames());

        winningNumber = new ArrayList<>(Arrays.asList(1,2,3,4,5,6));
        bonusBall = 8;

        WinningLotto winningLotto = WinningLotto.of(winningNumber, bonusBall);
        winningLotto.checkWinning(lottoGames.getLottoGames());
        OutputView.displayWinningResults(winningLotto);
    }


}
