package domain;

import validator.LottoValidator;

public class Purchase {
    public static final int ONE_LOTTO_PRICE = 1000;
    private final int amount;
    private final int autoGeneratedLottoQuantity;
    private final int manualGeneratedLottoQuantity;

    public Purchase(int amount, int autoGeneratedLottoQuantity, int manualGeneratedLottoQuantity) {
        LottoValidator.assertValidPurchaseAmount(amount);
        //수량이 올바른지 확인
        this.amount = amount;
        this.autoGeneratedLottoQuantity = autoGeneratedLottoQuantity;
        this.manualGeneratedLottoQuantity = manualGeneratedLottoQuantity;
    }

    public int getAmount() {
        return amount;
    }

    public int getAutoGeneratedLottoQuantity() {
        return autoGeneratedLottoQuantity;
    }

    public int getManualGeneratedLottoQuantity() {
        return manualGeneratedLottoQuantity;
    }

    public static int purchaseableQuantity(int amount) {
        if ((amount < 0) || (amount % ONE_LOTTO_PRICE != 0)) {
            return 0;
        }
        return amount / ONE_LOTTO_PRICE;
    }
}
