package domain;

import java.util.List;

public class Purchase {
    public static final int PRICE = 1000;
    private final int amount;
    private final List<Lotto> autoGeneratedLotto;

    public Purchase(int amount, List<Lotto> autoGeneratedLotto) {
        this.amount = amount;
        this.autoGeneratedLotto = autoGeneratedLotto;
    }

    public int getAmount() {
        return amount;
    }

    public static int purchaseableQuantity(int amount) {
        return amount / PRICE;
    }

    public int getTotalPurchaseQuantity() {
        return amount / PRICE;
    }

    public List<Lotto> getAutoGeneratedLotto() {
        return autoGeneratedLotto;
    }
}
